[package]
authors = ["Benjamin Wasty <benny.wasty@gmail.com>"]
categories = ["rendering"]
description = "Simple glTF 2.0 viewer (WIP)"
include = [
    "Cargo.toml",
    "Cargo.lock", # Note: currently ignored by `cargo package`, see rust-lang/cargo#2263
    "**/*.rs",
    "src/shaders/*.*",
]
keywords = ["glTF", "3D", "model", "scene", "viewer"]
license = "Unlicense"
name = "gltf-viewer"
readme = "README.md"
repository = "https://github.com/bwasty/gltf-viewer"
version = "0.1.0-pre"

[badges]

[badges.travis-ci]
branch = "master"
repository = "bwasty/gltf-viewer"

[dependencies]
bitflags = "0.9.1"
cgmath = "0.14.1"
clap = "2.25.1"
futures = "0.1.14"
futures-cpupool = "0.1.5"
gl = "0.6.3"
glutin = "0.9.2"
image = "0.14.0"
reqwest = "0.7.2"
log = "0.3"
simplelog = "0.4.2"
itertools = "0.6.1"

[dependencies.gltf]
# version = "0.9.2"
git = "https://github.com/gltf-rs/gltf"
branch = "v1.0"
features = ["names"]

[dependencies.gltf-importer]
# version = "0.9.2"
git = "https://github.com/gltf-rs/gltf"
branch = "v1.0"

[dependencies.gltf-utils]
# version = "0.9.2"
git = "https://github.com/gltf-rs/gltf"
branch = "v1.0"

# [patch.crates-io]
# gltf = { git = "https://github.com/bwasty/gltf", branch = "bounds"}
# gltf-json = { git = "https://github.com/bwasty/gltf", branch = "bounds"}

# [profile.dev]
# opt-level = 2
# debug = false

# [profile.release]
# opt-level = 3
# lto = true
