[package]
authors = ["Benjamin Wasty <benny.wasty@gmail.com>"]
categories = ["rendering"]
description = "Simple glTF 2.0 viewer (WIP)"
include = [
    "Cargo.toml",
    "Cargo.lock", # Note: currently ignored by `cargo package`, see rust-lang/cargo#2263
    "**/*.rs",
    "src/shaders/*.*",
]
keywords = ["glTF", "3D", "model", "scene", "viewer"]
license = "Unlicense"
name = "gltf-viewer"
readme = "README.md"
repository = "https://github.com/bwasty/gltf-viewer"
version = "0.0.4-pre"

[badges]

[badges.travis-ci]
branch = "master"
repository = "bwasty/gltf-viewer"

[dependencies]
cgmath = "0.14.1"
clap = "2.25.1"
futures = "0.1.14"
futures-cpupool = "0.1.5"
gl = "0.6.3"
glutin = "0.9.2"
# TODO!: explicit dependency really needed?
image = "0.14.0"
reqwest = "0.7.2"

[dependencies.gltf]
# version = "0.7.0"
git = "https://github.com/alteous/gltf"
branch = "mikk-tspace"
features = ["names"]

[patch.crates-io]
gltf = { path = "../gltf"}

# [profile.dev]
# opt-level = 2
# debug = false
